### ISSUE TITLE
Move Unifi Controller to Pi

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#106]
either Pi Zero or something else.

**Comment by CCOSTAN** [comment]
http://www.lowefamily.com.au/2016/06/02/installing-ubiquiti-unifi-controller-5-on-raspberry-pi/

**Comment by mattthhdp** [comment]
You should put it on a Docker container really worth it, as the unifi controller are not really using any ressource

**Comment by CCOSTAN** [comment]
@mattthhdp can you run docker on a pi for just the UniFi? Or is docker more of a take over kinda software? I reLly need to read up on this. :)

**Comment by mattthhdp** [comment]
I dont know about docker and the pi (but pretty sure that the answer is yes, because thats exactly how the "new hass io" is working Rasp--Docker--Home Assistant)


i run my setup in a VM and docker let me use a virtual machine with a bunch of software inside it so it really maximize my ressource

so docker is a software that you install on pretty much any os



before i was having
1-vm for Unifi controller (what as waste ... because this vm was alway idling) (512 mb ram)

1-vm for home assistant (512 mb ram)

1-vm for ubuntu share server (1 gb ram)
and so on

now i have 1 vm with ubuntu server, installed docker in it and in docker i have 3 (i lie a bunch of container (that a vm but for docker)

and this vm is using 512 mb ram
Docker---unifi controller .. using like 52mb ram

             |_home assistant .. using like 100mb ram at max
             |_my file server .... using a big 100 ram too


so as you can it really help optimizing the resources


Hope i make it clear, feel free to ask 😃

sorry for my bad english im a french canadian


________________________________
De : Carlo Costanzo <notifications@github.com>
Envoyé : 11 août 2017 03:39
À : CCOSTAN/Home-AssistantConfig
Cc : Jaune; Mention
Objet : Re: [CCOSTAN/Home-AssistantConfig] Move Unifi Controller to Pi (#106)


@mattthhdp<https://github.com/mattthhdp> can you run docker on a pi for just the UniFi? Or is docker more of a take over kinda software? I reLly need to read up on this. :)

**Comment by CCOSTAN** [comment]
@mattthhdp - Do you have a docker-compose file I can peek at for your unifi install?

**Comment by CCOSTAN** [comment]
unifi:
    image: jacobalberty/unifi:latest
    container_name: "Unifi"
    restart: always
    volumes:
      - ./unifi/data:/unifi/data
    ports:
     - 3478:3478/udp
     - 10001:10001/udp
     - 6789:6789/tcp
     - 8080:8080/tcp
     - 8880:8880/tcp
     - 8443:8443/tcp
     - 8843:8843/tcp
    environment:
     - TZ=America/New_York
    network_mode: "host"
