### ISSUE TITLE
restart Homebridge when HASS is restarted.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#114]
Thanks @dale3h for the code.

This will restart HomeBridge when Hass is up and running to prevent issues seen in the past. 

>What user do you run pm2 as? If homeassistant, then it should be simple. If not homeassistant user, try:
>Run sudo visudo as your non-homeassistant user (pi if you're on rpi). Then add the following to the bottom:
```# Allow homeassistant to use pm2
homeassistant ALL=(ALL) NOPASSWD: /usr/bin/pm2
```

**Comment by dale3h** [comment]
I found another way that might be more reliable, but it involves moving Homebridge to systemd instead of using pm2.

#### `home-assistant.service`
Add the following two lines below `[Unit]` to your `/etc/systemd/system/home-assistant.service` file:

```
Wants=homebridge.service
Before=homebridge.service
```

It should look similar to this afterward:

```
[Unit]
Description=Home Assistant
Wants=homebridge.service
Before=homebridge.service
After=network.target
```

#### `homebridge.service`

Now create the file `/etc/systemd/system/homebridge.service` and add these contents:

```
[Unit]
Description=Homebridge
BindsTo=home-assistant.service
After=home-assistant.service

[Service]
Type=simple
User=homebridge
ExecStartPre=/bin/sleep 60
ExecStart=/usr/bin/homebridge -U /var/lib/homebridge
RestartSec=10
Restart=on-failure
```

* If you wish to use `homebridge` as the user, you can create it by running `sudo useradd -M --system homebridge`
* Change the Homebridge configuration path (`/var/lib/homebridge`) to suit your needs. Just make sure that this config path is writeable by the user
* Double-check the path to your `sleep` executable: `which sleep`
* Double-check the path to your `homebridge` executable: `which homebridge`

#### `daemon-reload`

Now run `sudo systemctl daemon-reload`, and then `sudo systemctl enable homebridge.service`.

Homebridge should now start (with a 60s delay) and stop with Home Assistant!

**Comment by CCOSTAN** [comment]
Hey @dale3h, This looks great!  I've implemented these changes into my system and also flagged this thread for `reference code`.  Once small issue on the bottom but otherwise looks great.  Homebridge started right up.  I did change the user to run as hass to keep it all simple.

```bash
The unit files have no [Install] section. They are not meant to be enabled
using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
```
