### ISSUE TITLE
Find and check out roomba ir remote

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#188]

**Comment by CCOSTAN** [comment]
Or maybe wifi.. 

https://github.com/Norien/Home-Assistant-Config/issues/85

**Comment by nalipaz** [comment]
Maybe you should check out a general purpose infrared transceiver of sorts. I picked up an Irdroid USB Transceiver for $38 with shipping and used their drivers to setup my infrared remote controlled vacuum (not roomba). 

The great thing about the transceiver is I can send and receive infrared signals so I pick up tv signals and can send tv signals since I situated the transceiver above the tv. The bad thing however is the outbound IR is of course pretty dependent on direction it is pointed, I mean it is fairly strong IR from the little dongle and it bounces off walls fairly successfully but it needs to be pointed in the general vicinity of the units you wish to control if you want it to always succeed in hitting the target. If your roomba leaves the room then you would need to wait for it's return before being able to control again. If you can do it through wifi that would be more reliable.

**Comment by nalipaz** [comment]
So looking again at Irdroid's products, it seems they now have a [wi-fi to infrared adapter](http://www.irdroid.com/irdroid-wifi-version-3-0/). That is a nice solution to the directional issue. If you could use the micro-usb wire and tap into the power charging of the roomba then the transceiver could actually  piggy-back on the roomba while it roams. It isn't clear to me if you would only need to the buy the wi-fi adapter (and it comes with the IR transceiver) or you need to purchase a transceiver separately. If it is the wi-fi adapter only then the picture is a little misleading.

**Comment by DanielGalle** [comment]
Or maybe use a Broadlink RM3 mini: [http://www.ibroadlink.com/rm/](url)

You can get this one for around $15 on AliExpress and GearBest!

**Comment by nalipaz** [comment]
@DanielGalle that is a cool device that I have yet to see. How well does it work through walls for IR? It seems like it indicates it does, but I would like to know for my own project what you might know about it.

**Comment by DanielGalle** [comment]
@nalipaz I can't tell you right now. It's still sitting in my office with a lot of other stuff that needs to be set up :(

But I thought it was cheap and I could automate TV and AppleTV and so on in the bedroom.

**Comment by nalipaz** [comment]
@DanielGalle how would you see that Broadlink RM3 integrating with hass? I mean I see how you set it up in Android but what would be the interface for letting hass send it things, does it have an api endpoint or something? Currently I am using `irsend` with the wi-fi to infrared adapter I have connected to my hass server and that works well with the exception of walls and other obstructions.

**Comment by CCOSTAN** [comment]
Moved on to Neato Vaccuums. 

[Neato](https://amzn.to/2zoFx3S)
