### ISSUE TITLE
Add Epson Printer color level sensors.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#283]
https://community.home-assistant.io/t/epson-wf-3540-ink-level-monitoring/21813

**Comment by CCOSTAN** [comment]
http://www.vmwareinfo.com/2017/12/unboxing-epson-expression-premium-et.html

**Comment by gsemet** [comment]
Sorry for that, but I am about to stole your script ! Same printer, same happiness with it ! That's my way of thanking you for your great work on your HA system (and keeping it open for everyone to have a look and be inspired).

For information, printing from your iOS works but you won't have the full quality with it (because of the default AirPrint driver).
If you use mac, you can still print via AirPrint but you need to install the "ET-7750" driver and so choose this driver when adding your printer with AirPlay. (Choose the standalone driver, not the bundle package). Printed a lot of comparison charts to get this. A3 prints are amazing, but since the inks are mid-level dye, they won't last a lot without UV protection.

**Comment by CCOSTAN** [comment]
Very Glad you are enjoying the Repo @gsemet !  Steal away! :) We all share, take, improve and give back.. 

One thing I have noticed with the 7750 is the ink heads can dry out if you don't print often.  So make sure you don't let it sit for a long time without printing..  My CYAN tube dried out and I'm having a hard time getting full color back.  (i might make a follow up video to this one : 
https://www.vcloudinfo.com/2017/12/unboxing-epson-expression-premium-et.html

**Comment by gsemet** [comment]
Yes, printing every 1-2 weeks is necessary, like every inkjet printer, maybe a little bit more with this one.
It is really important for the nozzle. My previous printer costed me way too much in unclogging. I was wondering, maybe you may have an idea, is there a way to print every so often (1-2 weeks) a color test page. If you follow someone like [joserodriguez](https://www.youtube.com/watch?v=aRLSFccrceU), he says it is obvious to print regularly to stay clog free. But printer manufacturer never provide this "print at least one color test page ever n days" feature. Maybe this would be a mission for Home Assistant...

**Comment by CCOSTAN** [comment]
That is SUCH a great idea to have full color table automatically printed once a week to prevent clogging..

hmm .. Really need to think about this now.. :)

**Comment by gsemet** [comment]
Maybe only the print page is enough, all nozzles are used for it and it should do the job. I however did not found an API to trigger this job easily...

**Comment by CCOSTAN** [comment]
Something like this might work.. 

https://www.tenforums.com/drivers-hardware/109440-how-automate-printing-test-page-once-per-week.html

Not Home Assistant but just a scheduled task on a PC.
