### ISSUE TITLE
Set up VPN in the house.

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#398]
https://blog.ambar.cloud/tutorial-set-up-openvpn-with-docker-compose/

**Comment by crowland88** [comment]
I see your running pihole does pihole not support a vpn ?

**Comment by CCOSTAN** [comment]
@crowland88 - Not that I know of.  Pi-Hole just knocks down internet ads.   I am looking to put soemthing like OpenVPN up so that I can connect securely from the outside to my internal network.

**Comment by sanghviharshit** [comment]
Have you looked into PiVPN yet? I have set it up on separate Pi and works like a charm!

**Comment by onerealfunnyguy** [comment]
Have you looked at PFSense yet?,  I have been using this for year now.
https://amzn.to/2uwZui8
Should handle everything pihole does plus so much more.

**Comment by CCOSTAN** [comment]
@sanghviharshit - I have a Pi and Pi zERO BOTH LOOKING FOR A PURPOSE.. You might have just found them. :)

**Comment by crowland88** [comment]
please take a look at this [https://www.hackerarsenal.com/products/winx](url)

**Comment by smitt04** [comment]
Wireguard is the new hotness for VPN technology, I have implemented it both at home and work and love it.

**Comment by TUISTERa** [comment]
> Wireguard is the new hotness for VPN technology, I have implemented it both at home and work and love it.

Care to share more info ?

**Comment by smitt04** [comment]
https://www.wireguard.com/

It is fast and cryptographically sound and is pretty easy to set up.  It is much faster than other technologies like IPSec or OpenVPN. It uses udp traffic instead of tcp.

And if you use something like this https://github.com/trailofbits/algo you get an even easier setup. Algo started with IPSec but offer wireguard now.  They will setup your server and clients.  Anytime you need to add more clients just run the script and it will create clients and update server. And the best part is that they create QR codes for each client. So if you need to add the wireguard onto your phone you just scan the QR code and you are all set.

**Comment by CCOSTAN** [comment]
Thanks for all the suggestions.  I think Nabu Casa has eliminated this need for me now.  (Plus I barely leave the house). and when I do, I don't need access back to it. :)
