### ISSUE TITLE
(IFTTT) Blink ALL lights at 9:30 to remind me to take medicine. (also Alexa Alert)

### ISSUE THREAD

**Issue by escapologyBB** [CCOSTAN/Home-AssistantConfig#42]
Hello!

I was looking for you in the Gitter chat to ask you this but I couldn't see you, and I didn't want to forget so I thought I would post my question here.  I've looked through these configuration files and my extreme newness means that I had not been able to work out how you've done this, you see I have to take a particular medication at 9 o'clock in the morning every 72 hours which is a weird time interval to have to remember.

At the moment I have an IFTTT recipe which scans a Google calendar for the words "patch day", and then when it finds it it flashes every  LIFX light bulb in the house green.  This is great when it works, but it isn't 100% reliable so if my Internet goes out I don't get the reminder, and consequences of not having this medication can be horrendous and I will do you the solid of sparing you the details.

Having Alexa announced that I need to take my medication as well as having the lights going would be brilliant, but I just cannot work out how you've done it, would you be to point me in the right direction please?

Thanks in advance, and thanks for the help you given me in the chat room, it's really appreciated.  :-)

**Comment by CCOSTAN** [comment]
Mine is not really sophisticated at all.  I have a regular alexa alarm. (every night at 9:30).  I also have an alarm on my Iphone for the same time.  and then just a regular IFTTT alert that uses the time channel and the hue channel to blink the lights.  

I was thinking about using an input_boolean to keep track of IF I take my medicine (using alexa/emulated_hue to turn it off) so that if I come home late past 9:30, I get a TTS reminding me to take it for the night.   and then resetting the input_boolean at like 2am for the next day.  Something like that might work for your 72 hour schedule. 

I did just finish some date logic that could be REALLY useful for you.  Check out : 
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/script/monthly_colors_scene.yaml#L33-L84

The dates are pretty easy to populate.  You can just make 100 entries for the entire year to trigger values..  The other thing you could do is just test if the current day is divisible by 3.  If it is, today is a medicine day.  You might have to verify if that works at the end of the year though. 

Using %j from http://strftime.org/
and then something like this : http://stackoverflow.com/questions/8002217/how-do-you-check-whether-a-number-is-divisible-by-another-number-python

Good Luck!
CARLO.

P.S. If you figure out some code, please be sure to leave a comment with your code on this issue to help others.  (and me!)
