### ISSUE TITLE
Consider Time of Day sensor

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#511]
Not sure If I need this or not.  Might make the automations more complex.  Need to investigate. 

https://www.home-assistant.io/components/binary_sensor.tod/

**Comment by thejeffreystone** [comment]
Best use case I have found so far is for the audible notifications. I have a time of day sensor called quiet_time from midnight to 7am. So at I can "turn off" my audible notifications when the kid goes to bed, or when guests come over, which really just routes any audible notifications to my google homes in the kitchen and the master bedroom instead of the main house speaker until quiet_time which silences all but alerts. 

Haven't found a use outside of that, that can't be covered by the sun sensor, but I'm going to watch this one just in case you find a use case.

**Comment by CCOSTAN** [comment]
Yeah.  I have bed sensors so we use those to enable quiet time (just shutting the whole house AMP really). 
I need to give my media player redirection some more love but basically the same set up.   

I think this one just makes the YAML a bit simpler but harder to decipher/unwind since it would involve a sensor.  Gonna pass on this one.
