### ISSUE TITLE
Travis Build Error from Custom_Component - YouTube

### ISSUE THREAD

**Issue by CCOSTAN** [CCOSTAN/Home-AssistantConfig#788]
@pinkywafer - Do you know what I need to add to my travis/yml to allow for successful testing of the custom_component Youtube?

Getting Platform Error. 
```bash
Failed config
  General Errors: 
    - Platform error sensor.youtube - Integration 'youtube' not found.
```

https://travis-ci.org/github/CCOSTAN/Home-AssistantConfig/builds/702704721

Thanks!  You're my goto Travis Expert. :) 

Related: #720

**Comment by CCOSTAN** [comment]
```bash
Failed config
  General Errors: 
    - Platform error sensor.youtube - Integration 'youtube' not found.
```

**Comment by pinkywafer** [comment]
Are you running any other custom components that are configured in the configuration.yaml?

The reason I'm asking - Travis is installing HA without any custom components. For anything configured through UI,(.storage folder) that's fine, as it is not checked, but anything in configuration.yaml will be evaluated... So no YouTube sensor as the custom component is not installed. 

It should be possible to install just the YouTube component in Travis... I'll have a look later when I'm not working.
Otherwise, an easy solution (which is what I'm doing at the moment) would be to include the custom_components folder in your repo

**Comment by pinkywafer** [comment]
Okay, to add just the component to the build:
At the end of the install section, add:
``` yaml
  - git clone https://github.com/custom-components/youtube.git youtube_component/
  - mv youtube_component/custom_components config/custom_components

```

**Comment by pinkywafer** [comment]
So now, really it's a choice of what you want to do...
### 1. Include your custom_components folder in the repo
  + Benefits
    + Tracks all your component updates
    + all components are pulled in with one pull for a fresh install etc
  + Disadvantages
    + More maintenance (component update commits)
    + Only the version you're using is in the repo

### 2. git clone in travis.yml
  + Benefits
    + No custom components in repo
  + Disadvantages
    + you have to decide which version or the component to use (may not match what you're using:
      + master branch
      + Specific tag
      + Latest

**Comment by CCOSTAN** [comment]
This is awesome @pinkywafer .. Thank you.  I think I am going to do Option 2 right now.  I don't mind having the Custom_components folder in the repo but I'm always afraid that some component will store something secret in that folder and it'll get swept up into the repo.. like a log or yaml or something.   But this is awesome.. Thanks!
